name: Release Tweet
on:
  release:
    types: [released]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |

            # create a new tweet file from a branch

            await github.pulls.create({
              owner: context.repo.owner,
              repo: "tweets",
              body: context.payload.body,
              title:"New tweet",
              head: open-sauced/tweets,
              base: master
            })

