name: Release Tweet
on:
  release:
    types: [released]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)
