name: Release Tweet
on:
  release:
    types: [released]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |

            # create a new tweet file from a branch

            await github.pulls.create({
              owner: context.repo.owner,
              repo: "tweets",
              body: context.payload.body
              title:"New tweet" # release tag
              head
              base
            })

